version: '3.9'

networks:
  backend:
    name: ${CONTAINER_NAME}_backend
    driver: 'bridge'

services:
  pgsql:
    platform: ${PLATFORM}
    stop_grace_period: 30s
    build:
      context: ./pgsql
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    container_name: ${CONTAINER_NAME}_postgres
    image: ${CONTAINER_NAME}_postgres
    environment:
      TZ: ${TIMEZONE}
      PGTZ: ${TIMEZONE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.data/pgsql:/var/lib/postgresql/data/
      - ./pgsql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:5432
    networks:
      - backend
    restart: unless-stopped
    profiles:
      - full
      - pgsql
  php-fpm:
    platform: ${PLATFORM}
    build:
      context: ./php-fpm
      args:
        - TIMEZONE=${PHP_FPM_TZ}
        - COMPOSER_VERSION=${PHP_FPM_COMPOSER_VERSION}
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - INSTALL_IMAGE_OPTIMIZERS=${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS}
        - INSTALL_IMAGEMAGICK=${PHP_FPM_INSTALL_IMAGEMAGICK}
        - INSTALL_FFMPEG=${PHP_FPM_INSTALL_FFMPEG}
        - INSTALL_WKHTMLTOPDF=${PHP_FPM_INSTALL_WKHTMLTOPDF}
        - INSTALL_NODE=${PHP_FPM_INSTALL_NODE}
        - NVM_DIR=${NVM_DIR}
        - NODE_VERSION=${NODE_VERSION}
        - CUSTOM_COMMAND=${PHP_FPM_CUSTOM_COMMAND}
    container_name: ${CONTAINER_NAME}_php-fpm
    image: ${CONTAINER_NAME}_php-fpm
    volumes:
      - ../:/var/www/
      - ./.data/cache/psalm/:/var/www/docker-php8.2/.data/cache/psalm
      - ./.data/cache/stan/:/var/www/docker-php8.2/.data/cache/stan
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    ports:
      - "${PHP_FPM_XDEBUG_PORT}:9003"
    expose:
      - "9000"
    environment:
      - TZ=${PHP_FPM_TZ}
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    networks:
      - backend
    restart: unless-stopped
  nginx:
    platform: ${PLATFORM}
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    container_name: ${CONTAINER_NAME}_nginx
    image: ${CONTAINER_NAME}_nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ../:/var/www/
      - ./.data/logs/nginx/:/var/log/nginx
    networks:
      - backend
    restart: unless-stopped
  redis:
    platform: ${PLATFORM}
    build:
      context: ./redis
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    container_name: ${CONTAINER_NAME}_redis
    image: ${CONTAINER_NAME}_redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./.data/redis:/data
    networks:
      - backend
    restart: unless-stopped
    profiles:
      - full
      - redis